# Generated by Django 4.2.4 on 2023-10-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grades', '0002_alter_assignment_points_alter_assignment_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.FloatField(default=0.0),
        ),
    ]
